trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/tmp/
    mkdir -p $(Build.ArtifactStagingDirectory)/tmp-gzip/
    cd $(Build.SourcesDirectory)
    rsync -a $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/buildfacts/BuildArtifact*/tmp/ $(Build.ArtifactStagingDirectory)/tmp/
    rsync -a $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/buildfacts/BuildArtifact*/tmp-gzip/ $(Build.ArtifactStagingDirectory)/tmp-gzip/
  displayName: 'clean staging dir'
  workingDirectory: $(Build.SourcesDirectory)


- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'buildartifacts'
