trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:
- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber) $(Build.ArtifactStagingDirectory) $(Build.SourcesDirectory)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- script: 'echo "Hello World" > hello1.txt'
  displayName: 'Write hello1'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush
- script: 'mkdir -p $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp1'
  displayName: 'cf 1'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web
- script: 'echo "Hello World" > file1.txt'
  displayName: 'Write hello1'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp1

- template: copy-publish.yml@self
  parameters:
    artifactName: 'MyCustomFolder1'
    contents: | 
      $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp1/**
      $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush/**

- script: 'echo "Hello World" > hello2.txt'
  displayName: 'Write hello2'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush
- script: 'mkdir -p $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp2'
  displayName: 'cf 2'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web
- script: 'echo "Hello World" > file2.txt'
  displayName: 'Write hello2'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp2

- template: copy-publish.yml@self
  parameters:
    artifactName: 'MyCustomFolder2'
    contents: | 
      $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp2/**
      $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush/**

- script: 'echo "Hello World" > hello3.txt'
  displayName: 'Write hello3'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush
- script: 'mkdir -p $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp3'
  displayName: 'cf 3'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web
- script: 'echo "Hello World" > file3.txt'
  displayName: 'Write hello3'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp3

- template: copy-publish.yml@self
  parameters:
    artifactName: 'MyCustomFolder3'
    contents: | 
      $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp3/**
      $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush/**

- script: 'mkdir -p $(Build.ArtifactStagingDirectory)/tmp-gzip/hashed-assets'
  displayName: 'create folder'
  workingDirectory: $(Build.ArtifactStagingDirectory)

- script: 'mkdir -p $(Build.ArtifactStagingDirectory)/tmp'
  displayName: 'create folder'
  workingDirectory: $(Build.ArtifactStagingDirectory)

- script: 'ls'
  displayName: 'list folders'
  workingDirectory: $(Build.ArtifactStagingDirectory)

- task: DownloadPipelineArtifact@2
  displayName: 'Download artifacts'
  inputs:
    patterns: '*[1-3]/Tailspin.SpaceGame.Web/**/*'
    path: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts

- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts/**/Aayush/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/tmp-gzip/hashed-assets'
    flattenFolders: true
    cleanTargetFolder: true

- script: 'find $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts -name "Aayush*" -type d –delete'
  displayName: 'delete hashed-assests'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts

- script: 'ls'
  displayName: 'list folders'
  workingDirectory: $(Build.ArtifactStagingDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts/MyCustomFolder1/Tailspin.SpaceGame.Web/

- task: CopyFiles@2
  inputs:
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts/MyCustomFolder*/**/Tailspin.SpaceGame.Web/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/tmp'
    cleanTargetFolder: true      

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'BuildArtifacts'
    