trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber) $(Build.ArtifactStagingDirectory) $(Build.SourcesDirectory)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- script: 'echo "Hello World" > hello1.txt'
  displayName: 'Write hello1'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush

- template: copy-publish.yml@self
  parameters:
    artifactName: 'MyCustomFolder1'
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush/hello1.txt'

- script: 'echo "Hello World" > hello2.txt'
  displayName: 'Write hello2'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush

- template: copy-publish.yml@self
  parameters:
    artifactName: 'MyCustomFolder2'
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush/hello2.txt'

- script: 'echo "Hello World" > hello3.txt'
  displayName: 'Write hello3'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush

- template: copy-publish.yml@self
  parameters:
    artifactName: 'MyCustomFolder3'
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Aayush/hello3.txt'

- script: 'mkdir -p $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp1'
  displayName: 'cf 1'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web
- script: 'echo "Hello World" > file1.txt'
  displayName: 'Write hello1'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp1
- template: copy-publish.yml@self
  parameters:
    artifactName: 'expFolder1'
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp1/**'

- script: 'mkdir -p $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp2'
  displayName: 'cf 2'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web
- script: 'echo "Hello World" > file2.txt'
  displayName: 'Write hello2'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp2
- template: copy-publish.yml@self
  parameters:
    artifactName: 'expFolder2'
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp2/**'

- script: 'mkdir -p $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp3'
  displayName: 'cf 3'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web
- script: 'echo "Hello World" > file3.txt'
  displayName: 'Write hello3'
  workingDirectory: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp3
- template: copy-publish.yml@self
  parameters:
    artifactName: 'expFolder3'
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/exp3/**'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'

- script: 'mkdir -p $(Build.ArtifactStagingDirectory)/tmp-gzip/hashed-assets'
  displayName: 'create folder'
  workingDirectory: $(Build.ArtifactStagingDirectory)

- script: 'mkdir -p $(Build.ArtifactStagingDirectory)/tmp'
  displayName: 'create folder'
  workingDirectory: $(Build.ArtifactStagingDirectory)

- script: 'ls'
  displayName: 'list folders'
  workingDirectory: $(Build.ArtifactStagingDirectory)

- task: DownloadPipelineArtifact@2
  displayName: 'Download artifacts'
  inputs:
    patterns: '*[1-3]/Tailspin.SpaceGame.Web/**/*'
    path: $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts

- template: copy-publish.yml@self
  parameters:
    artifactName: 'BuildArtifacts'
    contents: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts/**/*.txt'
    flattenFolders: true
    targetFolder: '$(Build.ArtifactStagingDirectory)/tmp-gzip/hashed-assets'

- template: copy-publish.yml@self
  parameters:
    artifactName: 'BuildArtifacts'
    contents: '!$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/DownloadedArtifacts/**/Aayush/**'
    flattenFolders: true
    targetFolder: '$(Build.ArtifactStagingDirectory)/tmp'
    
- task: DotNetCoreCLI@2
  displayName: 'Publish the project - Release'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    artifactName: 'TopFolder'
  condition: succeeded()