trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/BuildArtifacts
    for dir in $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/buildfacts/BuildArtifact*/*/
    do
      mkdir -p $(Build.ArtifactStagingDirectory)/BuildArtifacts/${dir##*/}
    done

    for dir in $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/buildfacts/BuildArtifact*/*/
    do
      dir=${dir%*/}
      echo "${dir##*/}"
      cp -rf $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/buildfacts/BuildArtifact*/${dir##*/}/* $(Build.ArtifactStagingDirectory)/BuildArtifacts/${dir##*/}/
    done
  displayName: 'clean staging dir'
  workingDirectory: $(Build.SourcesDirectory)


- publish: $(Build.ArtifactStagingDirectory)/BuildArtifacts
  artifact: BuildArtifacts
  displayName: Publish Build artifacts
