trigger:
  - "*"

pool:
  vmImage: "ubuntu-18.04"
  demands:
    - npm

variables:
  buildConfiguration: "Release"

steps:

  - stage: build_multi_window
    displayName: Build Multi-Window
    dependsOn: []
    jobs:
      # Build Multi-Window experience
      - job: build_multi_window
        displayName: Build Multi-Window
        container: teams-client-tmp
        timeoutInMinutes: 90
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK 6.x'
            inputs:
              packageType: sdk
              version: '6.x'

          - task: Npm@1
            displayName: 'Run npm install'
            inputs:
              verbose: false

  - stage: dependent_job
    displayName: Dependent Job
    dependsOn: []
    jobs:
      # Build Multi-Window experience
      - job: dependent_job
        displayName: dependent_job
        container: teams-client-tmp
        timeoutInMinutes: 90
        steps:          
          - script: node ./rest.ts
            displayName: "make rest call"
            workingDirectory: $(Build.SourcesDirectory)