trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/artifacts/hashed-assets
    cd $(Build.SourcesDirectory)
    rsync -a $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/artifacts/*/hashed-assets/ $(Build.ArtifactStagingDirectory)/artifacts/hashed-assets/
  displayName: 'clean staging dir'
  workingDirectory: $(Build.SourcesDirectory)


- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/artifacts
    artifactName: 'buildartifacts'
