trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'

steps:

- script: |

    for dir in $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/buildfacts/BuildArtifact*/*/
    do
      echo "hello ${dir##*/}"
      mkdir -p $(Build.ArtifactStagingDirectory)/BuildArtifacts/${dir##*/}/
    done
    
    cp -rf $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/buildfacts/BuildArtifact*/* $(Build.ArtifactStagingDirectory)/BuildArtifacts/
  displayName: 'clean staging dir'
  workingDirectory: $(Build.SourcesDirectory)


- publish: $(Build.ArtifactStagingDirectory)/BuildArtifacts
  artifact: BuildArtifacts
  displayName: Publish Build artifacts
